/* A parser generated by PackCC 3.1.0 */

#ifndef PCC_INCLUDED_DICESCRIPT_VM_PARSER_H
#define PCC_INCLUDED_DICESCRIPT_VM_PARSER_H

#include "dicescript_vm_internal.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dsfull_context_tag dsfull_context_t;

dsfull_context_t *dsfull_create(ds_vm_parser_t *auxil);
int dsfull_parse(dsfull_context_t *ctx, ds_ast_t **ret);
void dsfull_destroy(dsfull_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_DICESCRIPT_VM_PARSER_H */
