/* A parser generated by PackCC 3.1.0 */

#ifndef PCC_INCLUDED_DICESCRIPT_PARSER_H
#define PCC_INCLUDED_DICESCRIPT_PARSER_H

#include "dicescript_internal.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct dsv1_context_tag dsv1_context_t;

dsv1_context_t *dsv1_create(ds_parser_state_t *auxil);
int dsv1_parse(dsv1_context_t *ctx, ds_node_t **ret);
void dsv1_destroy(dsv1_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_DICESCRIPT_PARSER_H */
